// AUTO-GENERATED by scripts/generate-spinners.mjs — do not edit.
// Authored keyframes live in spinners/<name>/keyframes/*.svg; re-run
// `npm run generate:spinners` after adding or changing frames.

export interface SpinnerDef {
  readonly viewBox: string;
  /** Default ms per frame; overridable via the Spinner `delay` prop. */
  readonly delay: number;
  /** One pixl-style path per frame; an empty string is a blank frame. */
  readonly frames: readonly string[];
}

export const spinners = {
  "grow": {
    viewBox: "0 0 7 5",
    delay: 250,
    frames: [
      "M3 2H4V3H3V2Z",
      "M4 5H3V4H4V5ZM2 3H1L1 2L2 2L2 3ZM4 3H3V2L4 2V3ZM6 3H5V2L6 2V3ZM4 1L3 1V0L4 0V1Z",
      "M2 5H1L1 4H2L2 5ZM4 5H3V4H4V5ZM6 5H5V4H6V5ZM2 3H1L1 2L2 2L2 3ZM4 3H3V2L4 2V3ZM6 3H5V2L6 2V3ZM2 1L1 1L1 0L2 0V1ZM4 1L3 1V0L4 0V1ZM6 1L5 1V0L6 0V1Z",
      "M1 0H6V5H1V0Z",
      "M2 5H1L1 4H2L2 5ZM4 5H3V4H4V5ZM6 5H5V4H6V5ZM2 3H1L1 2L2 2L2 3ZM4 3H3V2L4 2V3ZM6 3H5V2L6 2V3ZM2 1L1 1L1 0L2 0V1ZM4 1L3 1V0L4 0V1ZM6 1L5 1V0L6 0V1Z",
      "M4 5H3V4H4V5ZM2 3H1L1 2L2 2L2 3ZM4 3H3V2L4 2V3ZM6 3H5V2L6 2V3ZM4 1L3 1V0L4 0V1Z",
    ],
  },
  "pulse": {
    viewBox: "0 0 7 5",
    delay: 250,
    frames: [
      "M3 2H4V3H3V2Z",
      "M2 2H3V3H2V2Z M3 1H4V2H3V1Z M4 2H5V3H4V2Z M3 3H4V4H3V3Z",
      "M1 1H2V2H1V1Z M1 2H2V3H1V2Z M1 3H2V4H1V3Z M2 4H3V5H2V4Z M3 4H4V5H3V4Z M4 4H5V5H4V4Z M5 3H6V4H5V3Z M5 2H6V3H5V2Z M5 1H6V2H5V1Z M4 0H5V1H4V0Z M3 0H4V1H3V0Z M2 0H3V1H2V0Z",
    ],
  },
  "rotate": {
    viewBox: "0 0 7 5",
    delay: 250,
    frames: [
      "M1 0H2V1H1V0Z",
      "M5 0H6V1H5V0Z",
      "M5 4H6V5H5V4Z",
      "M1 4H2V5H1V4Z",
    ],
  },
  "rowing": {
    viewBox: "0 0 7 5",
    delay: 250,
    frames: [
      "M4 2H7V5H1V4H2V3H1V4H0V2H3V1H4V2ZM5 1H4V0H5V1ZM3 4H6V3H3V4Z",
      "M4 2H7V5H1V4H3V3H1V4H0V2H3V1H4V2ZM4 4H6V3H4V4ZM3 1H2V0H3V1Z",
      "M4 2H7V5H1V4H4V3H1V4H0V2H3V1H4V2ZM5 4H6V3H5V4ZM3 1H2V0H3V1Z",
      "M4 2H7V5H1V4H6V3H1V4H0V2H3V0H4V2Z",
    ],
  },
} satisfies Record<string, SpinnerDef>;

export type SpinnerName = keyof typeof spinners;

export const spinnerNames = Object.keys(spinners) as SpinnerName[];
